### ISSUE TITLE
doc error missed comas

### ISSUE THREAD

**Issue by futurist** [j2css/j2c#11]
below doc in https://github.com/j2css/j2c#global-class-and-animation-names
cannot compile and missed comas in js object:

````
s = j2c.sheet({
    "@global": {
        "ul.foo": {
            font_size: "2em",
        }
    }
    "p:global(.bar)" :{
        color:"#f00"
        animation_name: ":global(baz)"
    },
    "@keyframes :global(baz)": {
        // define the global "baz" animation here.
    }
})
````

missed 2 comas and cannot complied

**Comment by pygy** [comment]
Many thanks for the report. That's what happens when you type code examples without trying them (or correctly proofreading them)...
