### ISSUE TITLE
@extend not working reliable ?

### ISSUE THREAD

**Issue by daslicht** [j2css/j2c#22]
Hi,
i have the following code, the extend on line 105 works locally but not in [js-bin/fiddle](http://jsfiddle.net/daslicht/qe805q4q/12/)?

What am I missing please?

**Comment by daslicht** [comment]
Looks like I was using the next branch which no longer has extend but compose :)

**Comment by daslicht** [comment]
@extend is broken for me with version 0.11.2

**Comment by daslicht** [comment]
```
            '.links': {
                border: 'solid 1px',
                padding: '10px',
                display: 'block',
                width: '150px',
                float: 'left',
                clear: 'right',
                textAlign: 'center',
                textDecoration: 'none'
            },
            '.active': {
                '@extend': ['.links'],
                fontWeight: 'bold',
                color: 'red'

            }
```

results in active state : 

```
                fontWeight: 'bold',
                color: 'red'

```

**Comment by pygy** [comment]
That's expected, but `yourSheet.active` should read something like `"active_j2c_xxx link_j2c_yyy"`. 

That's how it works under the hood, and why it only works when the target class is a local.

**Comment by pygy** [comment]
Note that it you are doing that within a single sheet you might as well do

            '.links, .active': {
                border: 'solid 1px',
                padding: '10px',
                display: 'block',
                width: '150px',
                float: 'left',
                clear: 'right',
                textAlign: 'center',
                textDecoration: 'none'
            }

**Comment by daslicht** [comment]
But how is the active than different from the link ?

where to put 
```
   fontWeight: 'bold',
                color: 'red'
```
?

**Comment by pygy** [comment]
As before:

            /*...*/,
            '.active': {
                '@extend': ['.links'],
                fontWeight: 'bold',
                color: 'red'

            }

**Comment by pygy** [comment]
If you read this by mail, I Ninja edited the previous comment...
