### ISSUE TITLE
use with webpack style-loader

### ISSUE THREAD

**Issue by futurist** [j2css/j2c#25]
How to pass `j2c` generated stylesheet into webpack [style-loader](https://github.com/webpack/style-loader) ?

Or, maybe add an API to **use** / **unuse** stylesheet, like [addStyle](https://github.com/webpack/style-loader/blob/master/addStyles.js) and [usable](https://github.com/webpack/style-loader/blob/master/useable.js)

Or, maybe passed into [cssnext](https://github.com/MoOx/postcss-cssnext) ?

That way it's strong in daily use.

**Comment by futurist** [comment]
Maybe [m_j2c](https://github.com/mithriljs-cn/m_j2c) is good for apply j2c?

**Comment by pygy** [comment]
Alternatively, https://github.com/j2css/mithril-j2c can work too.

Ultimately, a small helper that directly creates DOM nodes would probably be ideal...

**Comment by futurist** [comment]
I've made this lib [cssobj](https://github.com/cssobj/cssobj) to solve the issue mentioned, and solve more problem from my daily work.
