### ISSUE TITLE
require('j2c') vs require('j2c')()

### ISSUE THREAD

**Issue by barryels** [j2css/j2c#35]
Perhaps I'm missing something, but the docs seem to be incorrect in stating how to 'require' this lib, i.e.

```
'use strict';

var j2c_test1 = require('j2c');
console.log(j2c_test1.sheet); // undefined

var j2c_test2 = require('j2c')();
console.log(j2c_test2.sheet); // [function body]
``` 

Note the function call for `j2c_test2`
I'm using Browserify with Babelify, if that makes any difference :)

**Comment by pygy** [comment]
What version are you using?

Oooh... It looks like I published `v1.0.0-4` on the main release channel on NPM, which is an error. The API has changed a bit, and I haven't updated the docs yet (this is a pre-release version)... Appologies for the confusion, it's time for a v0.11.3 to fix the mess...

**Comment by pygy** [comment]
v0.11.3 is out

If you're still interrested in trying the v1 preview, the change log is in the corresponding PR: #15

**Comment by barryels** [comment]
Ahh, i see, cool. Thanks for the quick feedback. Was on v1.0.0-4
